export const AGE_COUNTER = 'AGE_COUNTER';
export const WEIGHT_COUNTER = 'WEIGHT_COUNTER';
export const HEIGHT_COUNTER = 'HEIGHT_COUNTER';
export const GENDER_CHANGED = 'GENDER_CHANGED';
export const GET_BMI_RESULT = 'GET_BMI_RESULT';
export const MODAL_VISIBILITY = 'MODAL_VISIBILITY';
